import json
from collections import defaultdict
from datetime import date

from detlab.models import Detection

SEVERITY_SCORES = {
    "low": 25,
    "medium": 50,
    "high": 75,
    "critical": 100,
}

SEVERITY_COLORS = {
    "low": "#ffe766",
    "medium": "#ffb84d",
    "high": "#ff6666",
    "critical": "#cc0000",
}


def _score_for_detections(detections: list[Detection], score_by: str) -> int:
    if score_by == "count":
        return min(len(detections), 4) * 25

    return max(SEVERITY_SCORES[detection.severity] for detection in detections)


def _color_for_detections(detections: list[Detection]) -> str:
    highest = max(detections, key=lambda detection: SEVERITY_SCORES[detection.severity])
    return SEVERITY_COLORS[highest.severity]


def generate_navigator_layer(
    detections: list[Detection],
    name: str = "DetLab ATT&CK Coverage",
    domain: str = "enterprise-attack",
    score_by: str = "severity",
) -> str:
    if score_by not in {"severity", "count"}:
        raise ValueError("score_by must be either 'severity' or 'count'")

    grouped: dict[str, list[Detection]] = defaultdict(list)
    for detection in detections:
        grouped[detection.attack.technique].append(detection)

    techniques = []
    for technique_id, technique_detections in sorted(grouped.items()):
        comment_lines = [
            f"{detection.id}: {detection.title} ({detection.severity}, {detection.status})"
            for detection in sorted(technique_detections, key=lambda item: item.id)
        ]
        techniques.append(
            {
                "techniqueID": technique_id,
                "score": _score_for_detections(technique_detections, score_by),
                "color": _color_for_detections(technique_detections),
                "comment": "\n".join(comment_lines),
                "enabled": True,
                "metadata": [
                    {"name": "detections", "value": str(len(technique_detections))},
                    {
                        "name": "highest_severity",
                        "value": max(
                            technique_detections,
                            key=lambda detection: SEVERITY_SCORES[detection.severity],
                        ).severity,
                    },
                ],
            }
        )

    layer = {
        "name": name,
        "versions": {
            "attack": "16",
            "navigator": "5.1.0",
            "layer": "4.5",
        },
        "domain": domain,
        "description": "Generated by DetLab from validated detection content.",
        "filters": {
            "platforms": [
                "Linux",
                "macOS",
                "Windows",
                "Network",
                "PRE",
                "Containers",
                "Office Suite",
                "SaaS",
                "Google Workspace",
                "IaaS",
                "Azure AD",
            ]
        },
        "sorting": 0,
        "layout": {
            "layout": "side",
            "aggregateFunction": "average",
            "showID": False,
            "showName": True,
            "showAggregateScores": False,
            "countUnscored": False,
        },
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffffff", "#ff6666"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "Low", "color": SEVERITY_COLORS["low"]},
            {"label": "Medium", "color": SEVERITY_COLORS["medium"]},
            {"label": "High", "color": SEVERITY_COLORS["high"]},
            {"label": "Critical", "color": SEVERITY_COLORS["critical"]},
        ],
        "metadata": [
            {"name": "generated_by", "value": "DetLab"},
            {"name": "generated_on", "value": date.today().isoformat()},
            {"name": "score_by", "value": score_by},
        ],
    }

    return json.dumps(layer, indent=2)
