services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./detections:/workspace/detections:ro

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - api
